# Data Extraction & Preprocessing

In [2]:
#The files in which data of t-20 matches are available is in Yaml so we need to extract it in dataframe for data preprocessing. 
#Dataset used for this model=Cricsheet- A Retrosheet for Cricket(t-20 matches only) [Kaggle].

In [3]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm

In [5]:
filenames=[]
for file in os.listdir('data'):
    filenames.append(os.path.join('data',file))

In [6]:
filenames[0:5]

['data\\1001349.yaml',
 'data\\1001351.yaml',
 'data\\1001353.yaml',
 'data\\1004729.yaml',
 'data\\1007655.yaml']

In [8]:
final_dfs_list = [] 
counter = 1

for file in tqdm(filenames):
    with open(file, 'r') as f:
        df = pd.json_normalize(safe_load(f))
        df['match_id'] = counter
        final_dfs_list.append(df) 
        counter += 1


final_df = pd.concat(final_dfs_list, ignore_index=True)

final_df

100%|██████████████████████████████████████████████████████████████████████████████| 1432/1432 [10:55<00:00,  2.19it/s]

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,...,info.outcome.by.runs,info.match_type_number,info.neutral_venue,info.outcome.method,info.outcome.result,info.outcome.eliminator,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-18,2,[2017-02-17],male,T20,5.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-19,2,[2017-02-19],male,T20,2.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-23,1,[2017-02-22],male,T20,NaN,Australia,20,...,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.9,2016-09-12,1,[2016-09-05],male,T20,NaN,Hong Kong,20,...,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.9,2016-06-19,1,[2016-06-18],male,T20,NaN,Zimbabwe,20,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1427,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-03-05,2,[2016-03-04],male,T20,6.0,Pakistan,20,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1428,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.9,2016-03-08,1,[2016-03-06],male,T20,8.0,India,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1429,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.9,2016-02-03,1,[2016-02-03],male,T20,NaN,Netherlands,20,...,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1430,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2016-09-12,1,[2016-09-06],male,T20,NaN,Australia,20,...,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1431,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.9,2016-09-12,1,[2016-09-09],male,T20,4.0,Australia,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Dataframe info

In [10]:
# These features are available in the dataset.

In [18]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1432 entries, 0 to 1431
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   innings                  1432 non-null   object
 1   info.dates               1432 non-null   object
 2   info.gender              1432 non-null   object
 3   info.match_type          1432 non-null   object
 4   info.outcome.by.wickets  662 non-null    float64
 5   info.outcome.winner      1386 non-null   object
 6   info.overs               1432 non-null   int64
 7   info.player_of_match     1269 non-null   object
 8   info.teams               1432 non-null   object
 9   info.toss.decision       1432 non-null   object
 10  info.toss.winner         1432 non-null   object
 11  info.umpires             1410 non-null   object
 12  info.venue               1432 non-null   object
 13  match_id                 1432 non-null   int64
 14  info.city                1240 non-null   object
 15  info.outcome.by.runs     724 non-null    float64
 16  info.match_type_number   699 non-null    float64
 17  info.neutral_venue       328 non-null    float64
 18  info.outcome.method      51 non-null     object
dtypes: float64(4), int64(2), object(13)
memory usage: 212.7+ KB

In [20]:
final_df.drop(columns={'info.outcome.method','info.neutral_venue','info.match_type_number','info.outcome.by.runs','info.outcome.by.wickets'},inplace=True)

In [21]:
final_df

,innings,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.city
0,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-17],male,T20,Sri Lanka,20,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Melbourne Cricket Ground,1,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-19],male,T20,Sri Lanka,20,[DAS Gunaratne],"[Australia, Sri Lanka]",field,Sri Lanka,"[SD Fry, SJ Nogajski]","Simonds Stadium, South Geelong",2,Victoria
2,"[{'1st innings': {'team': 'Australia', 'delive...",[2017-02-22],male,T20,Australia,20,[A Zampa],"[Australia, Sri Lanka]",field,Sri Lanka,"[MD Martell, P Wilson]",Adelaide Oval,3,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",[2016-09-05],male,T20,Hong Kong,20,NaN,"[Ireland, Hong Kong]",bat,Hong Kong,"[R Black, AJ Neill]","Bready Cricket Club, Magheramason",4,Londonderry
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",[2016-06-18],male,T20,Zimbabwe,20,[E Chigumbura],"[Zimbabwe, India]",field,India,"[TJ Matibiri, RB Tiffin]",Harare Sports Club,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1427,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",[2016-03-04],male,T20,Pakistan,20,[Umar Akmal],"[Pakistan, Sri Lanka]",field,Pakistan,"[AK Chaudhary, Enamul Haque]",Shere Bangla National Stadium,1428,Mirpur
1428,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",[2016-03-06],male,T20,India,20,[S Dhawan],"[Bangladesh, India]",field,India,"[RSA Palliyaguruge, Shozab Raza]",Shere Bangla National Stadium,1429,Mirpur
1429,"[{'1st innings': {'team': 'Netherlands', 'deli...",[2016-02-03],male,T20,Netherlands,20,[Mudassar Bukhari],"[United Arab Emirates, Netherlands]",field,United Arab Emirates,"[CK Nandan, Sarika Prasad]",ICC Academy,1430,Dubai
1430,"[{'1st innings': {'team': 'Australia', 'delive...",[2016-09-06],male,T20,Australia,20,[GJ Maxwell],"[Sri Lanka, Australia]",field,Sri Lanka,"[REJ Martinesz, RR Wimalasiri]",Pallekele International Cricket Stadium,1431,NaN
1431,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",[2016-09-09],male,T20,Australia,20,[GJ Maxwell],"[Sri Lanka, Australia]",bat,Sri Lanka,"[REJ Martinesz, RSA Palliyaguruge]",R Premadasa Stadium,1432,Colombo

In [26]:
final_df['info.gender'].value_counts()

info.gender
male      966
female    466
Name: count, dtype: int64

In [27]:
# There is 466 match that were played by women so keeping records of only matches that were played by men.

In [30]:
final_df=final_df.loc[final_df['info.gender']=='male']

In [31]:
final_df['info.gender'].value_counts()

info.gender
male    966
Name: count, dtype: int64

In [32]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 966 entries, 0 to 1431
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   innings               966 non-null    object
 1   info.dates            966 non-null    object
 2   info.gender           966 non-null    object
 3   info.match_type       966 non-null    object
 4   info.outcome.winner   930 non-null    object
 5   info.overs            966 non-null    int64
 6   info.player_of_match  868 non-null    object
 7   info.teams            966 non-null    object
 8   info.toss.decision    966 non-null    object
 9   info.toss.winner      966 non-null    object
 10  info.umpires          956 non-null    object
 11  info.venue            966 non-null    object
 12  match_id              966 non-null    int64
 13  info.city             827 non-null    object
dtypes: int64(2), object(12)
memory usage: 113.2+ KB

In [33]:
final_df['info.overs'].value_counts()

info.overs
20    963
50      3
Name: count, dtype: int64

In [34]:
final_df=final_df.loc[final_df['info.overs']==20]

In [35]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 963 entries, 0 to 1431
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   innings               963 non-null    object
 1   info.dates            963 non-null    object
 2   info.gender           963 non-null    object
 3   info.match_type       963 non-null    object
 4   info.outcome.winner   927 non-null    object
 5   info.overs            963 non-null    int64
 6   info.player_of_match  865 non-null    object
 7   info.teams            963 non-null    object
 8   info.toss.decision    963 non-null    object
 9   info.toss.winner      963 non-null    object
 10  info.umpires          953 non-null    object
 11  info.venue            963 non-null    object
 12  match_id              963 non-null    int64
 13  info.city             825 non-null    object
dtypes: int64(2), object(12)
memory usage: 112.9+ KB

#Now at this time ,whole records contain data of all men t-20 matches and of 20 overs format.

In [37]:
final_df['info.match_type'].value_counts()

info.match_type
T20    963
Name: count, dtype: int64

#No need of feature like gender,match_type,overs so removing it

In [40]:
final_df.drop(columns={'info.gender','info.match_type','info.overs'},inplace=True)

In [41]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 963 entries, 0 to 1431
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   innings               963 non-null    object
 1   info.dates            963 non-null    object
 2   info.outcome.winner   927 non-null    object
 3   info.player_of_match  865 non-null    object
 4   info.teams            963 non-null    object
 5   info.toss.decision    963 non-null    object
 6   info.toss.winner      963 non-null    object
 7   info.umpires          953 non-null    object
 8   info.venue            963 non-null    object
 9   match_id              963 non-null    int64
 10  info.city             825 non-null    object
dtypes: int64(1), object(10)
memory usage: 90.3+ KB

In [42]:
import pickle
pickle.dump(final_df,open('dataset_01.pkl','wb'))

In [50]:
len(matches.iloc[0]['innings'][0]['1st innings']['deliveries'])

125

In [ ]:
# Extracting the ball by ball 1'st innings data only and each match categorised  by match id.

In [53]:
all_matches_list = [] 
count = 1
delivery_df = pd.DataFrame()
for index, row in matches.iterrows():
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count+=1
        continue
    count+=1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
            'match_id':match_id,
            'teams':teams,
            'batting_team':batting_team,
            'ball':ball_of_match,
            'batsman':batsman,
            'bowler':bowler,
            'runs':runs,
            'player_dismissed':player_of_dismissed,
            'city':city,
            'venue':venue
        })
    all_matches_list.append(loop_df)
    delivery_df = pd.concat(all_matches_list, ignore_index=True)

In [54]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...,...,...
115320,964,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium
115321,964,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium
115322,964,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium
115323,964,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium
115324,964,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium

In [55]:
delivery_df.to_csv('Dataset_02.csv',index=False)

In [56]:
delivery_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115325 entries, 0 to 115324
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          115325 non-null  int64
 1   teams             115325 non-null  object
 2   batting_team      115325 non-null  object
 3   ball              115325 non-null  float64
 4   batsman           115325 non-null  object
 5   bowler            115325 non-null  object
 6   runs              115325 non-null  int64
 7   player_dismissed  115325 non-null  object
 8   city              98557 non-null   object
 9   venue             115325 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 8.8+ MB

In [60]:
# now i donot have bowling team as i extracted it from teams feature.

In [57]:
def bowl(row):
    for team in row['teams']:
        if team !=row['batting_team']:
            return team

In [58]:
delivery_df['bowling_team']=delivery_df.apply(bowl,axis=1)

In [59]:
delivery_df.drop(columns=['teams'],inplace=True)

In [62]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,2,Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,2,Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,2,Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,2,Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
115321,964,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
115322,964,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
115323,964,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
115324,964,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [63]:
delivery_df['batting_team'].unique()

array(['Australia', 'Hong Kong', 'Zimbabwe', 'India', 'Bangladesh',
       'New Zealand', 'South Africa', 'England', 'West Indies', 'Ireland',
       'Afghanistan', 'Pakistan', 'United Arab Emirates', 'Scotland',
       'Oman', 'Papua New Guinea', 'Sri Lanka', 'Netherlands', 'Nepal',
       'Vanuatu', 'Philippines', 'United States of America', 'Germany',
       'Ghana', 'Uganda', 'Kenya', 'Namibia', 'Nigeria', 'Botswana',
       'Guernsey', 'Denmark', 'Jersey', 'Italy', 'Norway', 'Thailand',
       'Malaysia', 'Maldives', 'Singapore', 'Kuwait', 'Bermuda', 'Canada',
       'Cayman Islands', 'Portugal', 'Gibraltar', 'Spain', 'Bhutan',
       'Qatar', 'Iran', 'Belgium', 'Isle of Man', 'Bulgaria', 'Romania'],
      dtype=object)

In [68]:
#Now ,in this dataframe we have too many teams but they played very less match so there is possibilty of overfitting of model so we need to reduce teams to such teams who play frequently.

In [69]:
teams=['Australia','India','Bangladesh','New Zealand','South Africa','England','West Indies','Afghanistan','Pakistan', 'Sri Lanka']

In [70]:
delivery_df=delivery_df[delivery_df['batting_team'].isin(teams)]

In [71]:
delivery_df=delivery_df[delivery_df['bowling_team'].isin(teams)]

In [72]:
output=delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [73]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
115321,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
115322,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
115323,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
115324,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [74]:
output.to_csv('Dataset_03.csv',index=False)

In [75]:
# we get the features that we need for our model and thereafter we apply Feture engineering on this dataset.